[workspace]
resolver = "3"
members = ["crates/addresspass", "crates/addresspass-perf"]

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT OR Apache-2.0"
repository = "https://github.com/devrandom-labs/addresspass"

[workspace.dependencies]
addresspass = { path = "crates/addresspass" }
criterion = "0.8"
loom = "0.7"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }

